### ISSUE TITLE
Support for C++

### ISSUE THREAD

**Issue by MyCADDev** [namely/docker-protoc#103]
Hi 
Is there a plan to support C++ as a target language?

**Comment by mhamrah** [comment]
Should be easy enough to add as it's supported by the base grpc library.
Feel free to give a PR a shot, otherwise we'll keep this on our radar.

**Comment by MyCADDev** [comment]
Just created a Pull request

**Comment by MyCADDev** [comment]
The dockehub image for c++ works. Closing this issue.
