### ISSUE TITLE
docker file pulls github.com/golang/protobuf/proto-gen-go from master and not a tag/release

### ISSUE THREAD

**Issue by BradErz** [namely/docker-protoc#109]
Currently the docker image pulls the github.com/golang/protobuf/protoc-gen-go from master:
https://github.com/namely/docker-protoc/blob/master/Dockerfile#L42

Doing this with the latest released version of protoc `3.6.1` causes:
```bash
vendor/github.com/faceit/protos-generated/push-service/v1.0.0/go/push-service.pb.go:23:11: undefined: proto.ProtoPackageIsVersion3
```

The issue was discussed here is quite some detail:
https://github.com/golang/protobuf/issues/763

Is anyone getting arround this right now? Im about to open a PR to fix it otherwise. Following the install instructions in the README of https://github.com/golang/protobuf#installation

**Comment by mhamrah** [comment]
we got around this by bumping our various protobuf packages in our go projects to match

**Comment by BradErz** [comment]
Thanks for the response @mhamrah 

So your go projects also pull from the master of `golang/protobuf`? (i tried this and it works, but it feels super sketchy to have to do that)

I tried to pin the version of protoc-gen-go in the docker image
```docker
RUN go get -d -u github.com/golang/protobuf/protoc-gen-go \
    && git -C "$(go env GOPATH)"/src/github.com/golang/protobuf checkout v${golang_protobuf_version} \
    && go install github.com/golang/protobuf/protoc-gen-go
```

 However:
```docker
RUN go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
````
Then fails to install because it depends on `protoc-gen-go` and that branch is in a detached head state. I tried also to check back out the master branch of `protoc-gen-go` but then when the `protoc-gen-doc` is installed it overwrites the version of `protoc-gen-go` with the one of master again :roll_eyes:

**Comment by mhamrah** [comment]
We use go modules, and bumped to the latest.

**Comment by ido-namely** [comment]
Hi @BradErz , though the image is still building using protobuf latest, I think latest release addresses your issue (1.32_4). Please let me know.

**Comment by ido-namely** [comment]
`protoc-gen-go` is pinned as of #325, release [v1.48_0](https://github.com/namely/docker-protoc/releases/tag/v1.48_0)
