### ISSUE TITLE
Feature Request: Add typescript definition support for node (node-ts) with protoc-gen-ts plugin

### ISSUE THREAD

**Issue by HectorFriedman-Cintron** [namely/docker-protoc#111]
It would be nice to add typescript support for node via the protoc-gen-ts plugin.

I'm happy to take this on as a PR.

Potential Changes to Dockerfile
```
RUN set -ex && apk --update --no-cache add \
 ...
    nodejs \
    nodejs-npm \
    && npm i -g ts-protoc-gen

ENV PROTOC_GEN_TS_PATH /usr/local/lib/node_modules/protoc-gen-ts
```

Potential Changes to all/Entrypoint.sh
```
case $GEN_LANG in
...
"node(-ts)*") ...
...
esac
....
if [[ $GEN_LANG == "node-ts" ]]; then
    protoc \
        --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
        --ts_out=$OUT_DIR \
        ${PROTO_FILES[@]}
fi
```

**Comment by damiannolan** [comment]
This would be awesome!

**Comment by esilkensen** [comment]
I'd like to see this too 👍

Are you referring to [`ts-protoc-gen`](https://github.com/improbable-eng/ts-protoc-gen) (rather than `protoc-gen-ts`)?

**Comment by mhamrah** [comment]
PR's welcome!

**Comment by esilkensen** [comment]
Sounds good, I will give this a shot and hope to open a PR!

**Comment by mhamrah** [comment]
Believe we can close this now that's to #125 !
