### ISSUE TITLE
Please build namely/protoc-{the rest of them}

### ISSUE THREAD

**Issue by borg286** [namely/docker-protoc#12]
I tried doing docker pull namely/protoc-pypthon
and docker couldn't find it. Please build and push them to the docker repo.

**Comment by bobbytables** [comment]
Hi @borg286 ! Sorry about that, I'll make sure it's on Docker hub right now.

**Comment by bobbytables** [comment]
Python is good to go, I'll push these other ones. Thanks for reporting this.
