### ISSUE TITLE
Generates files under `root` user on Linux (Ubuntu 16.04)

### ISSUE THREAD

**Issue by yeenow123** [namely/docker-protoc#130]
I ran the `docker run` command on Ubuntu 16.04.  It however generates the files under root user.  Is there any workaround to not generate the files under root?  I believe this is because the Dockerfile doesn't specify a user and defaults to root.

**Comment by mhamrah** [comment]
You should be able to set the user and group via's docker's user flag. See https://docs.docker.com/engine/reference/run/#user

**Comment by yeenow123** [comment]
Ah yes, this worked. Thanks!
