### ISSUE TITLE
Buiding grpc-gateway for many service

### ISSUE THREAD

**Issue by phamtai97** [namely/docker-protoc#131]
Hi
First of all, I thank you because your project helped me a lot.
When i use feature [grpc-gateway](https://github.com/namely/docker-protoc#grpc-gateway-experimental), i had a problem that when using multiple services in many different proto files, grpc-gateway docker will only connect to one of those services.

Example:
I have file serviceA.proto
```proto
service ServiceA {
  rpc Ping (service.common.proto.MessagePing) returns (service.common.proto.MessagePong) {
    option (google.api.http) = {
      get: "/core/serviceA/ping/{timestamp}"
    };
  }
}
```
And I have file serviceB.proto
```proto
service ServiceB {
  rpc Ping (service.common.proto.MessagePing) returns (service.common.proto.MessagePong) {
    option (google.api.http) = {
      get: "/core/serviceA/ping/{timestamp}"
    };
  }
}
```
Then I run cmd:

```sh
$ docker run -v `pwd`:/defs namely/gen-grpc-gateway -f . -s ServiceA
```
I checked in the fun `SetupMux`  that only service A is registered because in cmd i only possible to configure option `-s serviceA`

I found a way to fix this by adding a function SetupMux(...) as follows:

```go
func SetupMux(ctx context.Context, cfg proxyConfig) *http.ServeMux {
...
err := gw.RegisterServiceAHandlerFromEndpoint(ctx, gwmux, cfg.backend, opts)
	if err != nil {
		logrus.Fatalf("Could not register gateway: %v", err)
	}

	err = gw.RegisterServiceBHandlerFromEndpoint(ctx, gwmux, cfg.backend, opts)
	if err != nil {
		logrus.Fatalf("Could not register gateway: %v", err)
	}
}
```

I have a solution to solve this problem. Can I create a pull request for this project?
@gxb5443 @mdkess

**Comment by ido-namely** [comment]
Hi @phamtai97 ,
sorry for the late response, does t[his](https://github.com/namely/docker-protoc/pull/174) pr solve this issue?

**Comment by phamtai97** [comment]
Hi @ido-namely.
Thank you. I also create [repo](https://github.com/zalopay-oss/docker-grpc-gateway) to use for many services.
