### ISSUE TITLE
Option to specify output path

### ISSUE THREAD

**Issue by borg286** [namely/docker-protoc#14]
Currently the scripts default to outputing generated files to the current directory. Would it be possible to have the scripts output the generated files to a different directory in its path, and then map it at run time to a different folder.

something like 
docker run -v `pwd`:/defs -v '/some/other/path':/gen namely/protoc-ruby

**Comment by borg286** [comment]
You'd probably need to consume a flag in the script to do this outputting, while falling back to the current behavior of outputing to the current (/defs) path.

**Comment by bobbytables** [comment]
@borg286 - Yeah I've wanted something like this as well. I've contemplated making a simple `bash` script that sits in your `PATH` that wraps the docker commands.

**Comment by bobbytables** [comment]
@gxb5443 - Thoughts?

**Comment by gxb5443** [comment]
I think that overly complicates things a bit for the docker images: I don't really like the idea of adding multiple volumes all willy-nilly. Although it would be cool to make a separate tool which uses these images to compile and then do whatever you want, like @bobbytables said.

**Comment by mdkess** [comment]
Fixed.
