### ISSUE TITLE
`paths=source_relative` support

### ISSUE THREAD

**Issue by kchodnicki** [namely/docker-protoc#142]
Are there plans to support `paths=source_relative` option for bindings generation?

**Comment by mhamrah** [comment]
I'll need to look into it. Happy to support PRs.

**Comment by mhamrah** [comment]
I've created https://github.com/grpckit/omniproto which takes a different approach to code generation for protofiles. It's declarative, and allows pass-through support for grpc plugin commands. It supports this parameter.

**Comment by ido-namely** [comment]
Hi @kchodnicki , please checkout the option to pass `--go-source-relative` which was added since you've opened this issue.
Thanks!
