### ISSUE TITLE
Upgrade to go-micro v2

### ISSUE THREAD

**Issue by Dominic-Preap** [namely/docker-protoc#182]
Is there any plan to upgrade go-micro plugin to v2?
https://github.com/micro/micro/tree/master/cmd/protoc-gen-micro

**Comment by mhamrah** [comment]
You can use https://GitHub.com/grpckit/grpckit as a base image, add the go
micro plugin to the new image layer, and use
https://GitHub.com/grpckit/omniproto to generate which passes through the
plug-in parameters to protoc.

**Comment by Dominic-Preap** [comment]
@mhamrah how can I add multi `--proto_path` or multiple `-I` in your yaml file?

**Comment by mhamrah** [comment]
See the example yaml file in the omniproto repo. It takes an array of files
or directories, and scans directories. If you need to tailor behavior you
can have multiple yaml config files and call omniproto with the config you
want to generate too.

**Comment by ido-namely** [comment]
Hi @Dominic-Preap ,
Can you please check latest version - 1.32_4?

**Comment by Dominic-Preap** [comment]
@ido-namely look good to me
