### ISSUE TITLE
namely/protoc-all:1.31_0 container on docker hub produces errors.

### ISSUE THREAD

**Issue by nibbleshift** [namely/docker-protoc#192]
I just noticed that our CI jobs are failing with the latest build of the protoc-all docker container on Docker hub.   We were using the latest tag (which is now 1.31_0) and it looks like the /opt/include directory in the container is missing files that were there in the previous container:

```
google/protobuf/timestamp.proto: File not found.
Import "google/protobuf/timestamp.proto" was not found or had errors.
"google.protobuf.Timestamp" is not defined.
```

As a short-term fix, I've tagged our container back to a previous release.   Just thought you might want to know.

Thanks

**Comment by villainy** [comment]
We ran into the same issue. It looks like some portion of the Google includes were removed in the 1.31 PR.

https://github.com/namely/docker-protoc/pull/190/files#diff-3254677a7917c6c01f55212f86c57fbfL96

**Comment by thejasn** [comment]
We also ran into the same issue. Is this an intended change ???

**Comment by piyush97** [comment]
Even we also ran into the same issue. Please `fix` it ASAP.

**Comment by 10yogi** [comment]
Even we also ran into the same issue. Please fix it ASAP.

**Comment by abe545** [comment]
Hi all - this was not an intended change. I'll look into restoring the missing protos.

**Comment by abe545** [comment]
It is building now - should be pushed in roughly 10 minutes.

**Comment by kevinmichaelchen** [comment]
I'm using
```
namely/protoc-all@sha256:b526a5eea24ea76886d3af25e8308196677413a3b00626abb00ba02f240e2299
```
from [this build](https://dev.azure.com/namely/protoc-all/_build/results?buildId=117&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86) and still running into errors:
```
Digest: sha256:b526a5eea24ea76886d3af25e8308196677413a3b00626abb00ba02f240e2299
Status: Downloaded newer image for namely/protoc-all@sha256:b526a5eea24ea76886d3af25e8308196677413a3b00626abb00ba02f240e2299
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
google/protobuf/timestamp.proto: File not found.
fluenteam/auth/v1/api.proto:13:1: Import "google/api/annotations.proto" was not found or had errors.
fluenteam/auth/v1/api.proto:14:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
fluenteam/auth/v1/api.proto:30:5: "google.protobuf.Timestamp" is not defined.
fluenteam/auth/v1/api.proto:35:5: "google.protobuf.Timestamp" is not defined.
```

**Comment by kevinmichaelchen** [comment]
I'm using
```
namely/protoc-all@sha256:b526a5eea24ea76886d3af25e8308196677413a3b00626abb00ba02f240e2299
```
from [this build](https://dev.azure.com/namely/protoc-all/_build/results?buildId=117&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86) and still running into errors:
```
Digest: sha256:b526a5eea24ea76886d3af25e8308196677413a3b00626abb00ba02f240e2299
Status: Downloaded newer image for namely/protoc-all@sha256:b526a5eea24ea76886d3af25e8308196677413a3b00626abb00ba02f240e2299
google/protobuf/descriptor.proto: File not found.
google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
google/protobuf/timestamp.proto: File not found.
myorg/auth/v1/api.proto:13:1: Import "google/api/annotations.proto" was not found or had errors.
myorg/auth/v1/api.proto:14:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
myorg/auth/v1/api.proto:30:5: "google.protobuf.Timestamp" is not defined.
myorg/auth/v1/api.proto:35:5: "google.protobuf.Timestamp" is not defined.
```

**Comment by resurtm** [comment]
Still have the same issue for the `namely/gen-grpc-gateway:latest`.
Using `namely/gen-grpc-gateway:1.30_0` fixed the issue, but it's a temporary fix.

**Comment by thejasn** [comment]
@abe545 even after #194, the issue seems to be present.

**Comment by lucasmarshall** [comment]
Definitely still broken with latest tag :(

**Comment by jesseduffield** [comment]
FWIW to work around this I'm calling `protoc` from within the container and passing `--proto_path=. --proto_path=/opt/include` to have it correctly resolve the imports. That works fine for me.
