### ISSUE TITLE
can protoc-gen-grpc-gateway be newer than v1.14.5

### ISSUE THREAD

**Issue by liuhuiping2013** [namely/docker-protoc#193]
the docker image **namely/gen-grpc-gateway:1.30_0** have warning [Getting a deprecation warning message](https://github.com/golang/protobuf/issues/1104)

could you please upgrade the protoc-gen-grpc-gateway?
in **namely/gen-grpc-gateway:1.30_0** when you run
```bash
# protoc-gen-grpc-gateway -version
Version dev, commit unknown, built at unknown
```
so, use **go get** in Dockerfile may not be the best practice?

**Comment by ido-namely** [comment]
Hi @liuhuiping2013 ,
Can you please check latest version 1.32_4?

**Comment by ido-namely** [comment]
Closing this as we upgraded to protoc-gen-grpc-gateway v2.
