### ISSUE TITLE
Go Protocol Buffers APIv2

### ISSUE THREAD

**Issue by Rossiar** [namely/docker-protoc#212]
The Go Team announced [a new api for protobuf](https://blog.golang.org/protobuf-apiv2) in March. Since then, a large scale migration has taken place that has left https://github.com/golang/protobuf as a legacy v1 implementation. 

We are currently using namely's protoc-all docker image and would like to begin generating proto using the [new v2 api](https://pkg.go.dev/mod/google.golang.org/protobuf), so I was wondering if you had any plans to upgrade this repository - or if we should fork and implement the changes just for us.

It will be a little tricky because the [recommended install path](https://developers.google.com/protocol-buffers/docs/reference/go-generated) is now:
```
go install google.golang.org/protobuf/cmd/protoc-gen-go
```

**Comment by owenthereal** [comment]
grpc-gateway was also updated to v2: https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.0.0

**Comment by ido-namely** [comment]
Hi @Rossiar , @owenthereal ,
I believe both of these issues were addressed in latest image - 1.32_4.
Please let me know if you find otherwise.

**Comment by Rossiar** [comment]
@ido-namely thanks! works very nicely for our Message definitions - it may take some time for me to verify that it works well with our full grpc binding (separate repo/purpose), so I'm happy for you to close this issue and I will open a new one if I find anything amiss.
