### ISSUE TITLE
Multiple documentation output

### ISSUE THREAD

**Issue by Alexfilus** [namely/docker-protoc#216]
Hi! I want to set multiple doc format outputs, something like 
--with-docs html,index.html;markdown,readme.md
Can I do that without running generator twice?

**Comment by ido-namely** [comment]
Hi @Alexfilus, I'm sorry for the late response.
That is more of a question to the author of [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc).
`--with-docs` is a wrapper around that plugin.
We don't intend to internally support this feature to avoid multiple executions of the docker image.
