### ISSUE TITLE
`paths=source_relative` support for  protoc-gen-validate

### ISSUE THREAD

**Issue by heliuchuan** [namely/docker-protoc#218]
I'd love for there to be source relative support for protoc-gen-validate.  Currently it seems theres no way to enable that with the script and the output files go to $OUT_DIR and then puts it in a path matching option go_package.

This is what I want to be able to do - 
envoyproxy/protoc-gen-validate#271

I've made a PR here
https://github.com/namely/docker-protoc/pull/217

**Comment by heliuchuan** [comment]
@ido-namely @alex-namely tagging so hopefully someone could take a peek at this

**Comment by ido-namely** [comment]
fixed in #217
