### ISSUE TITLE
Support grpc-gateway generate_unbound_methods option

### ISSUE THREAD

**Issue by juandemanjon** [namely/docker-protoc#226]
According to [gRPC API Configuration](https://github.com/grpc-ecosystem/grpc-gateway/blob/b4d54a0e3d1ea061661de197ce13e09e27ba8c41/docs/docs/mapping/grpc_api_configuration.md#generate_unbound_methods) the generate_unbound_methods produces the HTTP mapping even for methods without any `HttpRule` annotation.
It also works for `gen-openapiv2` plugin.

I am willing to push a pull request but first I would like to discuss the `entrypoint.sh` flag. My first thought was:

```
    echo " --generate_unbound_methods     Use with --with-gateway flag. Produce the HTTP mapping even for methods without any HttpRule annotation."
```
Please, let me know if you have any other name suggestion...

**Comment by ido-namely** [comment]
fixed in https://github.com/namely/docker-protoc/pull/227
