### ISSUE TITLE
Update grpc_tools_node_protoc_ts version to 5.3.2

### ISSUE THREAD

**Issue by masterkidan** [namely/docker-protoc#259]
Hello folks, 
Requesting an update to the typescript generation tools to the latest version. A bug was recently fixed https://github.com/agreatfool/grpc_tools_node_protoc_ts/issues/113 in the current version, this issue causes typescript to be broken if some oneOf types are used.

**Comment by masterkidan** [comment]
Some additional context: My team uses the built images from namely for protoc generation, hence need to update the defaults. 
I've opened a PR with the new version updated, please lmk if you have any further questions.

**Comment by ido-namely** [comment]
resolved in #301
