### ISSUE TITLE
Python GRPC out

### ISSUE THREAD

**Issue by parksj10** [namely/docker-protoc#269]
it doesn't seem possible with this docker to have "grpc_python_out" flag specified so `*_pb2_grpc.py` is output, is this correct?

**Comment by parksj10** [comment]
Nevermind, seems like [the script ](https://gist.github.com/bobbytables/2fab9ac9509867b5acfe2bb5693aee71) I was using used an older container... do you guys have an update bash script to go with this container for automating?

**Comment by ido-namely** [comment]
Hi @parksj10 ,
Sorry for the delayed response, we don't have an official script, but if you share with me what you're trying to achieve I might be able to help. Please let me know soon, otherwise I'll close this issue in a few days (which you are always welcome to reopen).
