### ISSUE TITLE
[Question] imported files not compiled

### ISSUE THREAD

**Issue by chris-kruining** [namely/docker-protoc#278]
Hi,

I am not sure if I am just having a massive brainfart or not.

What I am trying to achieve is to use this docker image to compile to both typescript and c# (for now only those two).
the generated files are then committed to the respective repo where the CI/CD is supposed to pick up the changed and compile, package, and deploy the new version of the lib for each language.

This is mostly working, but for both typescript and C# I am missing the imported types. is there a way for me to "inline" imported files into the output?

this is my proto source:
![image](https://user-images.githubusercontent.com/5786905/147957462-28d18284-38f8-464e-9b08-6770ff404271.png)

and this is the command calling the docker image from the azure pipelines config: `docker run -v `pwd`:/defs namely/protoc-all -i . -o $OUT_DIR -d ./service -l ${{ lang.generator }}`

`service/cms/v1/file.proto`:
![image](https://user-images.githubusercontent.com/5786905/147957882-9efc20b1-e577-4f38-9965-f73d63908b96.png)

the typescript does include a reference to the files but they do not exist:
![image](https://user-images.githubusercontent.com/5786905/147957755-897af844-9ce4-4c02-9504-fd30cb16c6cb.png)

is this a mistake on my part? Am I missing a flag? or can I not re-use other proto files like this

**Comment by ido-namely** [comment]
Hi @chris-kruining ,
I'm pretty sure that dependencies/imports are not automatically generated and they need to be generated explicitly with a similar command, i.e you'd need to execute:
```
docker run -v pwd:/defs namely/protoc-all -i . -o $OUT_DIR -d ./type -l ${{ lang.generator }}
```

**Comment by chris-kruining** [comment]
I seem to have gotten a bit further, the Typescript seems fine now, but does the container support the `--csharp_opt` flag? because it is not mentioned in the readme, but the help flag does show it

**Comment by chris-kruining** [comment]
to elaborate:

![image](https://user-images.githubusercontent.com/5786905/148363018-efe04270-61fc-4e76-900e-74afd550ee1c.png)

![image](https://user-images.githubusercontent.com/5786905/148363144-3ee2aebb-9156-412a-b217-eb9154b44c00.png)

If I am correctly interpreting the [docs](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#compiler_options) this should generate a folder structure based on the C# namespaces. but the error keeps being that it tries to create a duplicate file. Am I missing something or is the c#_opt maybe not passed to protoc properly?


I thought I had it for a sec, update the flag from `--csharp_opt=basename=Unifyned` to `--csharp_opt basename=Unifyned` but now it doesn't seems to generate anything at all anymore. I really am at a loss.

**Comment by chris-kruining** [comment]
ok, fixed it. apparently I can't run it with the `--help` flag. I removed it and now it works like a charm.

Sorry to have bothered you with my stupidity.
