### ISSUE TITLE
PHP files generator don't detect reserved class name Object

### ISSUE THREAD

**Issue by inkr-xx** [namely/docker-protoc#289]
Should be:
_If the message class name is reserved (for example, Empty), the prefix PB is prepended to the class name_
But class with name Object is still created.

```
syntax = "proto3";
package com.xxx.platform.iot.object;
option java_multiple_files = true;
message Object {
  optional string                     object_id = 1;
}
```
And result
`class Object extends \Google\Protobuf\Internal\Message`

google/protobuf version is not the latest. See:
https://github.com/protocolbuffers/protobuf/pull/8962

**Comment by ido-namely** [comment]
Hi @inkr-xx ,
I was able to reproduce the issue you reported even with our latest version.
However, we pull protobuf library from the `grpc/grpc` repo, which currently pins protobuf to 3.19.4 - https://github.com/grpc/grpc/tree/v1.47.0/third_party
So we will wait for that repo to pull a newer version of protobuf for it to apply in this project.
