### ISSUE TITLE
--with-gateway only works for go

### ISSUE THREAD

**Issue by mdkess** [namely/docker-protoc#29]
With csharp for example, you end up with

```
gen/pb-csharp
gen/pb-csharp/FunTimes.cs
gen/pb-csharp/FunTimesGrpc.cs
gen/pb-csharp/gateway
gen/pb-csharp/gateway/FunTimes.pb.gw.go
gen/pb-csharp/gateway/FunTimes.swagger.json
```

But the gateway needs the go Grpc client to work.

**Comment by mhamrah** [comment]
I think this is fine, because ideally this repo would have the templating support built in to generate a container with the entire proxy built in, using some `backend_host:backend_port` env variable to route traffic too. Ideally I see `--with-gateway` actually producing a container, not files.

**Comment by mdkess** [comment]
Fixed per offline discusison. Now --with-gateway is for go.
