### ISSUE TITLE
Feature Request: support stephenh/ts-proto as an alternative to improbable-eng/ts-protoc-gen

### ISSUE THREAD

**Issue by zaquestion** [namely/docker-protoc#291]
The current ts generator doesn't factor in these well known types and thus ends up generating ts that is painful to consume when wrapper types are in the mix. Another project `ts-proto` has specific handling for these which does the un/wrapping for you making it much easier to form and consume these types. https://github.com/stephenh/ts-proto#well-known-types

Would it be possible to get support added for `ts-proto` in addition to the current generator? Similar to how both gogo and vanilla generators are supported for go.

**Comment by ido-namely** [comment]
Hi @zaquestion,
This change makes sense to me, is that something you are interested in contributing to this repo?

**Comment by Checkroth** [comment]
@ido-namely

This is a feature that I would also like to use, so I took a crack at implementing it: https://github.com/namely/docker-protoc/pull/317

**Comment by ido-namely** [comment]
Addressed in #317 
Will be released in v1.47_2
