### ISSUE TITLE
protoc java:  --with-validator option not working

### ISSUE THREAD

**Issue by venkatduddu** [namely/docker-protoc#305]
I tried using the below command from the docker image 

```
/usr/local/bin/entrypoint.sh  --with-validator -d /defs/generated/proto/lakehouse/edge -i /defs/generated/proto -l java 
```

Generated java class doesn't have the validate method added. 

Looking at the code here https://github.com/namely/docker-protoc/blob/master/all/entrypoint.sh#L383-L396 looks like entry point is not considering validators for java it is only considering for go and gogo program languages.

Was this intentional or a bug?

**Comment by ido-namely** [comment]
Hi @venkatduddu ,
It seems like an oversight to me and not intentional.
Not sure if we have the bandwidth atm to fix this but PRs are welcome :)

**Comment by venkatduddu** [comment]
Hi @ido-namely 
See if this helps. 
https://github.com/namely/docker-protoc/pull/306

**Comment by ido-namely** [comment]
addressed in https://github.com/namely/docker-protoc/pull/306
