### ISSUE TITLE
Support node as a target language

### ISSUE THREAD

**Issue by synthecypher** [namely/docker-protoc#40]
Currently only the following languages are supported.

```
go ruby csharp java python objc
```

This is just a feature request to support `node`.

**Comment by mhamrah** [comment]
Thanks @synthecypher. You don't need to generate code for node applications so there's no need for node support in this container (it includes generators supplied with https://github.com/grpc/grpc-go, https://github.com/grpc/grpc and https://github.com/grpc/grpc-java. 

If you want to use grpc with node see the example where you load the proto file directly into your app: https://grpc.io/docs/tutorials/basic/node.html
