### ISSUE TITLE
Directory flag specifies maxdepth 1

### ISSUE THREAD

**Issue by blimmer** [namely/docker-protoc#61]
Today, pulling protofiles using the `-d` flag specifies a max-depth of 1.

https://github.com/namely/docker-protoc/blob/93b2381b888c691e2f4b3c0aac010f551cf361c2/all/entrypoint.sh#L174

Is there a specific reason for this? Can it be configurable?

We have a directory structure that looks like this:

```console
src/main/proto/company_pb
├── billing
│   └── events.proto
├── commons
│   ├── sqs
│   │   ├── sqs_attribute.proto
│   │   ├── sqs_attributes.proto
│   │   └── sqs_message.proto
│   └── timestamp.proto
```

So the `maxdepth` flag causes the command to fail out with this error
```
Missing input file.
```
because no files are passed to the underlying method.

**Comment by blimmer** [comment]
I just tried it out locally by just removing the `-maxdepth` option and things worked swimmingly for me! I'm happy to do a PR to this project.

The biggest question I have is whether or not we need to maintain the old behavior by default, or if we're comfortable just removing the `maxdepth` option. I'm open to doing it either way. Thoughts?

**Comment by mhamrah** [comment]
Submit a PR and I can test- should be okay.

**Comment by arturgspb** [comment]
If you like me in 2020+ don't understand why code with blocking max-depth come back - read https://github.com/namely/docker-protoc/pull/112
