### ISSUE TITLE
Ability to customize node "import styles"

### ISSUE THREAD

**Issue by blimmer** [namely/docker-protoc#71]
We would like to be able to customize the `js_out` portion of this `GEN_STRING`:

https://github.com/namely/docker-protoc/blob/3a872063daabf159aaed36a38d8467e2d00a1913/all/entrypoint.sh#L165-L167

Any thoughts on how you'd like to see that implemented?

**Comment by blimmer** [comment]
For context, we'd like to use the closure imports style instead of commonjs

https://github.com/google/protobuf/tree/master/js#closure-imports

**Comment by artificial-aidan** [comment]
Bump. Would also like to be able to customize import styles for `node` and `web`. Thoughts on implementation? Initial thought was to add a `--import-style` argument, that if it existed would override the `import_style` in the `GEN_STRING`.
