### ISSUE TITLE
Inconsistent package names

### ISSUE THREAD

**Issue by chambodn** [namely/docker-protoc#91]
Passing multiple different packages in *.proto files currently fails when using [protoc-gen-go](https://github.com/golang/protobuf/blob/b27b920f9e71b439b873b17bf99f56467623814a/protoc-gen-go/generator/generator.go#L655).

Consequently, the -d options in gen-proto does not work with multiple packages. 
```bash
/defs # entrypoint.sh  -d . -l go
Generating go files for . in gen/pb-go
2018/09/06 15:15:28 protoc-gen-go: error:inconsistent package names: package_one, package_two
--go_out: protoc-gen-go: Plugin failed with status code 1.
```
As a workaround we can have a simple interation other each proto file and called protoc compiler on that file in the **entrypoint.sh** script:

```bash
for filename in ${PROTO_DIR}/*.proto; do
    filename=${filename##*/} # remove path
    filename=${filename%.*} # remove extension

    rm -rf ${GO_OUTDIR}/${filename}
    mkdir ${GO_OUTDIR}/${filename}
    
    ${PROTOC} \
    --go_out=plugins=grpc:${GO_OUTDIR}/${filename} \
    -I ${PROTO_DIR} ${filename}.proto
done
```
Not sure if it's a pull request or an issue, but was wondering how you manage this kind of thing at namely?

**Comment by mhamrah** [comment]
Can you submit sample proto files and the command you run? 

We have a monorepo for all idls, and put each 'service' in a folder. Each service has its own package, and we generate each service separately via its folder.

**Comment by mhamrah** [comment]
Also, this seems to be pretty specific to the go compiler. See https://github.com/golang/protobuf/issues/159#issuecomment-203038389

**Comment by ido-namely** [comment]
I agree this is an issue of the compiler. I don't see a problem with invoking the image separately for each folder package.
Closing this for now, but happy to continue discussion if you still think it's an issue @chambodn
